from dataclasses import dataclass
from dataclasses import field
from pathlib import Path

import yaml


@dataclass(frozen=True)
class ImagePairConfig:
    """Manage data configuration for a single image pair, including two input images and corresponding ground truth file.

    Attributes:
        src_path (str | Path): Filename of the first source image, e.g., "1a_notredame.jpg".
        dst_path (str | Path): Filename of the second destination image, e.g., "1b_notredame.jpg".
        gt_path (str | Path): Ground truth filename for this image pair, e.g., "notredame.pkl".

            **Must use `pickle.load(f, encoding="latin1")`**, otherwise uint8 data generated by MATLAB cannot be decoded correctly.
    Example:
        >>> pickle.load(open("notredame.pkl", "rb"), encoding="latin1")

    .. Note::
        Deserialization returns a dict with the following keys:
        - x1 (np.ndarray): x coordinates of feature points in image A
        - y1 (np.ndarray): y coordinates of feature points in image A
        - x2 (np.ndarray): x coordinates of corresponding matching points in image B
        - y2 (np.ndarray): y coordinates of corresponding matching points in image B
    """

    src_path: str | Path
    dst_path: str | Path
    gt_path: str | Path

    def __post_init__(self) -> None:
        if isinstance(self.src_path, str):
            object.__setattr__(self, "src_path", Path(self.src_path))
        if isinstance(self.dst_path, str):
            object.__setattr__(self, "dst_path", Path(self.dst_path))
        if isinstance(self.gt_path, str):
            object.__setattr__(self, "gt_path", Path(self.gt_path))


@dataclass(frozen=True)
class PathConfig:
    """Manage project input/output paths and image pair configuration.

    Attributes:
        data_dir (str | Path): Image data directory, default ./data, supports string or Path object input.
        ground_truth_dir (str | Path): Ground truth data directory, default ./ground_truth, supports string or Path object input.
        output_dir (str | Path): Output result directory, default ./outputs, supports string or Path object input.
        image_pairs (list[ImagePairConfig]): List of image pairs, default includes notredame/rushmore/gaudi sets.
    """

    data_dir: str | Path = Path("./data")
    ground_truth_dir: str | Path = Path("./ground_truth")
    output_dir: str | Path = Path("./outputs")
    image_pairs: list[ImagePairConfig] = field(
        default_factory=lambda: [
            ImagePairConfig(
                src_path="1a_notredame.jpg",
                dst_path="1b_notredame.jpg",
                gt_path="notredame.pkl",
            ),
            ImagePairConfig(
                src_path="2a_rushmore.jpg",
                dst_path="2b_rushmore.jpg",
                gt_path="rushmore.pkl",
            ),
            ImagePairConfig(
                src_path="3a_gaudi.jpg", dst_path="3b_gaudi.jpg", gt_path="gaudi.pkl"
            ),
        ]
    )

    def __post_init__(self) -> None:
        # Convert parent directories to Path objects
        if isinstance(self.data_dir, str):
            object.__setattr__(self, "data_dir", Path(self.data_dir))
        if isinstance(self.ground_truth_dir, str):
            object.__setattr__(self, "ground_truth_dir", Path(self.ground_truth_dir))
        if isinstance(self.output_dir, str):
            object.__setattr__(self, "output_dir", Path(self.output_dir))

        # Concatenate data_dir / ground_truth_dir to each image pair filename to generate complete paths
        data_dir = Path(self.data_dir)
        gt_dir = Path(self.ground_truth_dir)
        concat_pairs = [
            ImagePairConfig(
                src_path=data_dir.joinpath(pair.src_path),
                dst_path=data_dir.joinpath(pair.dst_path),
                gt_path=gt_dir.joinpath(pair.gt_path),
            )
            for pair in self.image_pairs
        ]
        object.__setattr__(self, "image_pairs", concat_pairs)


@dataclass(frozen=True)
class LoggingConfig:
    """
    Manage logging behavior configuration.

    Attributes:
        log_dir (str | Path): Log output directory, default ./outputs/logs, supports string or Path object input.
        level (str): Log level, default "DEBUG", options "DEBUG"/"INFO"/"WARNING"/"ERROR"/"CRITICAL".
        retention (str): Log file retention time, default "7 days", supports natural language format, logs older than this will be auto-deleted.
        file_pattern (str): Log filename pattern, default "{time:YYYY-MM-DD_HH-mm-ss}.log", uses loguru time formatting, includes hour-minute-second to avoid conflicts from multiple runs on the same day.
    """

    log_dir: str | Path = Path("./outputs/logs")
    level: str = "DEBUG"
    retention: str = "7 days"
    file_pattern: str = "{time:YYYY-MM-DD_HH-mm-ss}.log"

    def __post_init__(self) -> None:
        if isinstance(self.log_dir, str):
            object.__setattr__(self, "log_dir", Path(self.log_dir))


@dataclass(frozen=True)
class AppConfig:
    """
    Aggregate global configuration entry point.

    Attributes:
        paths (PathConfig): Path and image pair configuration.
        logging (LoggingConfig): Logging-related configuration.
    """

    paths: PathConfig = field(default_factory=PathConfig)
    logging: LoggingConfig = field(default_factory=LoggingConfig)

    @classmethod
    def load_from_yaml(cls, yaml_path: str | Path) -> "AppConfig":
        try:
            with open(yaml_path, "r", encoding="utf-8") as f:
                config_dict = yaml.safe_load(f) or {}
                print(
                    f"\n\033[1;92m[SUCCESS] Configuration file loaded successfully: {yaml_path}\033[0m\n"
                )
        except yaml.YAMLError as e:
            raise ValueError(
                f"\033[1;91mInvalid YAML format in {yaml_path}: {e}\033[0m"
            ) from e
        except FileNotFoundError as e:
            raise ValueError(
                f"\033[1;91mConfiguration file not found: {yaml_path}\033[0m"
            ) from e

        paths_dict = config_dict.get("paths", {})
        logging_dict = config_dict.get("logging", {})

        # Process image_pairs list: convert dict list to ImagePairConfig object list
        image_pairs_list = paths_dict.get("image_pairs", [])
        paths_dict["image_pairs"] = [
            ImagePairConfig(**pair) for pair in image_pairs_list
        ]

        return cls(
            paths=PathConfig(**paths_dict),
            logging=LoggingConfig(**logging_dict),
        )

